theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: {{ site.github.repository_url }}/archive/refs/tags/v0.2.0.zip
  tar_url: {{ site.github.repository_url }}/archive/refs/tags/v0.2.0.zip
